### ISSUE TITLE
error

### ISSUE THREAD

**Issue by su314ka** [laertides/private_rsa_key_recovery#1]
Hi,

I receive below error.
Also if I try to install factordb again error.
There are some requirements to run the script?
Thanks!

D:\Downloads\private_rsa_key_recovery-master>D:\Downloads\private_rsa_key_recovery-master\recovery_private.py
Traceback (most recent call last):
  File "D:\Downloads\private_rsa_key_recovery-master\recovery_private.py", line 8, in <module>
    from factordb.factordb import FactorDB
ModuleNotFoundError: No module named 'factordb'
D:\Downloads\private_rsa_key_recovery-master>

D:\Downloads\private_rsa_key_recovery-master>pip install factordb
Collecting factordb
  Could not find a version that satisfies the requirement factordb (from versions: )
No matching distribution found for factordb
D:\Downloads\private_rsa_key_recovery-master>

**Comment by laertides** [comment]
yeah it actually needs factodb-pycli (pip install factordb-pycli)
note that this is untested and usually works with weak rsa keys, i developed it for a CTF challenge, 
im planning to work on it though uni has other plans for me

**Comment by su314ka** [comment]
No error now. Thanks!
